resources:
- ../base
- env-ops-configmap.yaml
- r70448e3/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r70448e3/revision-patch.yaml
  target:
    kind: Service
- path: r70448e3/routing-patch.yaml
  target:
    kind: Service