resources:
- ../base
- env-ops-configmap.yaml
- rf9da916/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rf9da916/revision-patch.yaml
  target:
    kind: Service
- path: rf9da916/routing-patch.yaml
  target:
    kind: Service