resources:
- ../base
- env-ops-configmap.yaml
- r2be6048/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r2be6048/revision-patch.yaml
  target:
    kind: Service
- path: r2be6048/routing-patch.yaml
  target:
    kind: Service