resources:
- ../base

images:
- name: image-registry.openshift-image-registry.svc.cluster.local:5000/team-a-tooling/quarkus-hello-world
  newTag: 049b185b9c698d0e2e7f29b5e6bce852558ef053

patchesStrategicMerge:
- custom-env.yaml