# Default values for quarkus-hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

quarkus-hello-world:
   quarkus-generic:
      env: 
         - name: ENVIRONMENT
           value: staging
      resources: 
         limits:
            cpu: 200m
            memory: 256Mi
         requests:
            cpu: 200m
            memory: 256Mi
