# Default values for quarkus-hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

quarkus-hello-world:
   quarkus-generic:
      resources: 
         limits:
            cpu: 300m
            memory: 256Mi
         requests:
            cpu: 300m
            memory: 256Mi