resources:
- ../base
- env-ops-configmap.yaml
- r6b73008/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r6b73008/revision-patch.yaml
  target:
    kind: Service
- path: r6b73008/routing-patch.yaml
  target:
    kind: Service