resources:
- ../base
- env-ops-configmap.yaml
- r1b644f0/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r1b644f0/revision-patch.yaml
  target:
    kind: Service
- path: r1b644f0/routing-patch.yaml
  target:
    kind: Service